name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"

      - name: Test the Frontend
        run: |
          cd frontend
          yarn install
          yarn test

      - name: Setup and Lunch the App from the Remote Machine (Hostinger)
        uses: appleboy/ssh-action@v0.1.10
        env:
          NODE_ENV: ${{ secrets.BACKEND_ENV_NODE_ENV }}
          BLOG_MONGODB_URI_ATLAS: ${{ secrets.BACKEND_ENV_BLOG_MONGODB_URI_ATLAS }}
          BLOG_PORT_EXPRESS: ${{ secrets.BACKEND_ENV_BLOG_PORT_EXPRESS }}
          BLOG_ACCESS_TOKEN_SECRET: ${{ secrets.BACKEND_ENV_BLOG_ACCESS_TOKEN_SECRET }}
        with:
          host: ${{ secrets.HOSTINGER_IP }}
          username: ${{ secrets.HOSTINGER_SSH_USERNAME }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          envs: NODE_ENV, BLOG_MONGODB_URI_ATLAS, BLOG_PORT_EXPRESS, BLOG_ACCESS_TOKEN_SECRET
          script: |
            pm2 delete daemon_blog
            cd sites
            rm -r Blog
            git clone https://github.com/HamzaLinge/Blog.git
            cd Blog/frontend
            yarn install
            yarn build
            rm -r node_modules
            cd ../backend/
            yarn install
            touch .env
            echo $NODE_ENV > .env
            echo $BLOG_MONGODB_URI_ATLAS >> .env
            echo $BLOG_PORT_EXPRESS >> .env
            echo $BLOG_ACCESS_TOKEN_SECRET >> .env
            pm2 start server.js --name daemon_blog --exp-backoff-restart-delay=100
