name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"

      - name: Test, Setup the Environment Variables and Build the Frontend
        run: |
          cd frontend
          yarn install
          yarn test
          mkdir .env
          echo ${{secrets.FRONTEND_ENV}} >> .env
          yarn build

      - name: Setup the Environment Variables for the Backend
        run: |
          cd backend
          mkdir .env
          echo ${{secrets.BACKEND_ENV}} >> .env

      - name: Prepare the Code for Deploy
        run: |
          mkdir blog
          mkdir blog/frontend
          mkdir blog/backend
          mv frontend/dist/* blog/frontend/
          mv backend/* blog/backend/

      - name: Remove, if exists, the Remote Code
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOSTINGER_VPS_IP }}
          username: ${{ secrets.HOSTINGER_VPS_USERNAME }}
          password: ${{ secrets.HOSTINGER_VPS_PASSWORD }}
          script: |
            rm -r /var/www/blog

      - name: Copy the Prepared Code to Hostinger's VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOSTINGER_VPS_IP }}
          username: ${{ secrets.HOSTINGER_VPS_USERNAME }}
          password: ${{ secrets.HOSTINGER_VPS_PASSWORD }}
          source: "blog"
          target: "/var/www/"

      - name: Lunch the Remote Backend Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOSTINGER_VPS_IP }}
          username: ${{ secrets.HOSTINGER_VPS_USERNAME }}
          password: ${{ secrets.HOSTINGER_VPS_PASSWORD }}
          script: |
            cd /var/www/blog
            ls -a
            cd backend
            ls -a
            cd ../frontend
            ls -a
