name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

#      - name: Install the Dependencies Test and Build the Frontend
#        run: |
#          cd frontend
#          yarn install
#          yarn test
#          yarn build

      - name: Test the Connexion with Hostinger
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOSTINGER_SSH_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: ${{ secrets.HOSTINGER_SSH_PORT }}
          script: |
            pwd
            ls
            cd domains/hamzacode.com/backends
            pwd
            ls
            cd ../public_html
            pwd
            ls

#      - name : Deploy the Backend
#        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
#        with:
#          server: ${{ secrets.HOSTINGER_FTP_HOST }}
#          username: ${{ secrets.HOSTINGER_USERNAME }}
#          password: ${{ secrets.HOSTINGER_PASSWORD }}
#          port: ${{ secrets.HOSTINGER_FTP_PORT }}
#          local-dir: backend/
#          server-dir: backends/blog/
#          dangerous-clean-slate: true
#
#      - name: Deploy the Frontend
#        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
#        with:
#          server: ${{ secrets.HOSTINGER_FTP_HOST }}
#          username: ${{ secrets.HOSTINGER_USERNAME }}
#          password: ${{ secrets.HOSTINGER_PASSWORD }}
#          port: ${{ secrets.HOSTINGER_FTP_PORT }}
#          local-dir: frontend/dist/
#          server-dir: public_html/blog/
#          dangerous-clean-slate: true
#
#      - name: Install the Dependencies and Lunch the Remote Backend
#        uses: appleboy/ssh-action@v0.1.10
#        with:
#          host: ${{ secrets.HOSTINGER_SSH_HOST }}
#          username: ${{ secrets.HOSTINGER_USERNAME }}
#          password: ${{ secrets.HOSTINGER_PASSWORD }}
#          port: ${{ secrets.HOSTINGER_SSH_PORT }}
#          script: |
#            cd domains/hamzacode.com/backends/blog
#            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
#            source ~/.bashrc
#            nvm install 18
#            npm ci
#            npm run start