name: Testing Workflow

on: push

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Backend Dependencies
        run: |
          cd backend
          yarn install
          ls -a
  frontend:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Frontend Dependencies
        run: |
          cd frontend
          yarn install
          ls -a
      - name: Run Frontend Tests
        run: | 
          cd frontend
          yarn test

      - name: Build Frontend
        run: |
          cd frontend
          yarn build
        if: success()