name: Testing

on:
  push:
    - master

jobs:
  checkout_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Go to the root project
        run: |
          pwd
          ls -a