name: Testing

on:
  push:
    branches:
      - master

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Go to the root project
        run: |
          pwd
          ls -a